/**
 * Dev-only mock data for visually testing the chef page redesign without a
 * running backend. Imported only when the API is unreachable.
 *
 * DELETE THIS FILE before shipping to production.
 */

export const MOCK_CHEF = {
  id: 999,
  user: { id: 999, username: 'chef_maria', first_name: 'Maria', last_name: 'Santos' },
  bio: 'Born and raised in the Bay Area with deep roots in Japanese and Mexican cuisine. I create intimate dining experiences that celebrate seasonal, local ingredients and the stories behind them.',
  experience: '12 years of professional cooking across Michelin-starred kitchens in San Francisco, followed by 3 years running a private chef practice.',
  is_live: true,
  is_on_break: false,
  is_verified: true,
  background_checked: true,
  food_handlers_cert: true,
  insured: true,
  insurance_expiry: '2027-06-15',
  mehko_active: true,
  permit_number: 'MEHKO-2025-1234',
  permitting_agency: 'Alameda County Environmental Health',
  county: 'Alameda',
  permit_expiry: '2027-01-31',
  profile_pic_url: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=200&h=200&fit=crop&crop=face',
  banner_url: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&h=600&fit=crop',
  photos: [
    { id: 1, image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop' },
    { id: 2, image_url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop' },
    { id: 3, image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop' },
    { id: 4, image_url: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop' },
  ],
  serving_postalcodes: [
    { postal_code: '94110', city: 'San Francisco', country: { code: 'US', name: 'United States' }, place_name: 'Mission District' },
    { postal_code: '94114', city: 'San Francisco', country: { code: 'US', name: 'United States' }, place_name: 'Castro' },
  ],
  review_summary: '4.9 (27 reviews)',
  sous_chef_emoji: '🧑‍🍳',
  calendly_url: null,
  default_currency: 'USD',
}

export const MOCK_EVENTS = [
  {
    id: 101,
    chef: MOCK_CHEF,
    meal: {
      id: 201,
      name: 'Poke Bowl Night',
      image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=640&h=480&fit=crop',
      description: 'Fresh ahi tuna poke bowls with edamame, mango, avocado, and house-made ponzu.',
    },
    meal_name: 'Poke Bowl Night',
    event_date: '2026-04-15',
    event_time: '18:00',
    order_cutoff_time: '2026-04-14T18:00:00Z',
    max_orders: 8,
    orders_count: 5,
    base_price: '95.00',
    current_price: '85.00',
    min_price: '75.00',
    status: 'open',
    description: 'Fresh ahi tuna poke bowls with edamame, mango, avocado, and house-made ponzu. Serves 2.',
  },
  {
    id: 102,
    chef: MOCK_CHEF,
    meal: {
      id: 202,
      name: 'Taco Tuesday Special',
      image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=640&h=480&fit=crop',
      description: 'Slow-braised birria tacos with consommé, house-made tortillas, and all the fixings.',
    },
    meal_name: 'Taco Tuesday Special',
    event_date: '2026-04-22',
    event_time: '18:30',
    order_cutoff_time: '2026-04-21T18:30:00Z',
    max_orders: 10,
    orders_count: 10,
    base_price: '75.00',
    current_price: '65.00',
    min_price: '55.00',
    status: 'closed',
    description: 'Slow-braised birria tacos with consommé, house-made tortillas, and all the fixings. Family style for 2-4.',
  },
  {
    id: 103,
    chef: MOCK_CHEF,
    meal: {
      id: 203,
      name: 'Omakase Sushi Night',
      image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=640&h=480&fit=crop',
      description: "Chef's selection of 8 courses featuring the freshest seasonal fish from the market.",
    },
    meal_name: 'Omakase Sushi Night',
    event_date: '2026-04-29',
    event_time: '19:00',
    order_cutoff_time: '2026-04-28T19:00:00Z',
    max_orders: 6,
    orders_count: 1,
    base_price: '150.00',
    current_price: '140.00',
    min_price: '120.00',
    status: 'scheduled',
    description: "Chef's selection of 8 courses featuring the freshest seasonal fish from the market. An intimate dining experience for 2.",
  },
]

export const MOCK_SERVICE_OFFERINGS = [
  {
    id: 301,
    chef: MOCK_CHEF.id,
    service_type: 'home_chef',
    service_type_label: 'In-Home Chef',
    title: 'In-Home Chef Experience',
    description: 'A professional chef arrives at your home to prepare a custom multi-course meal using the freshest local ingredients.',
    active: true,
    max_travel_miles: 15,
    currency: 'USD',
    tier_summary: ['One-time or recurring · 2-6 people · From $150'],
    tiers: [
      {
        id: 401,
        display_label: 'Dinner for Two',
        household_min: 1,
        household_max: 2,
        desired_unit_amount_cents: 15000,
        currency: 'USD',
        is_recurring: false,
        active: true,
        ready_for_checkout: true,
      },
      {
        id: 402,
        display_label: 'Family Dinner',
        household_min: 3,
        household_max: 6,
        desired_unit_amount_cents: 22000,
        currency: 'USD',
        is_recurring: false,
        active: true,
        ready_for_checkout: true,
      },
    ],
  },
  {
    id: 302,
    chef: MOCK_CHEF.id,
    service_type: 'weekly_prep',
    service_type_label: 'Weekly Meal Prep',
    title: 'Weekly Meal Prep',
    description: 'Fresh, portioned meals prepared weekly in your kitchen. Customize your menu each week.',
    active: true,
    max_travel_miles: 10,
    currency: 'USD',
    tier_summary: ['Recurring · 2-4 people · From $120/week'],
    tiers: [
      {
        id: 403,
        display_label: 'Couple Plan',
        household_min: 1,
        household_max: 2,
        desired_unit_amount_cents: 12000,
        currency: 'USD',
        is_recurring: true,
        recurrence_interval: 'weekly',
        active: true,
        ready_for_checkout: true,
      },
      {
        id: 404,
        display_label: 'Family Plan',
        household_min: 3,
        household_max: 4,
        desired_unit_amount_cents: 18000,
        currency: 'USD',
        is_recurring: true,
        recurrence_interval: 'weekly',
        active: true,
        ready_for_checkout: true,
      },
    ],
  },
]
