"""
Django settings for hood_united project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from datetime import timedelta
import logging

# Load environment variables - check for dev.env first (development), then .env (production)
if os.path.exists(os.path.join(os.path.dirname(__file__), '..', 'dev.env')):
    load_dotenv(os.path.join(os.path.dirname(__file__), '..', 'dev.env'))
else:
    load_dotenv()  # Try default .env file

# Helper function to convert string values to boolean
def str_to_bool(value, default=False):
    """
    Convert string values to boolean.
    Handles various string representations of True/False.
    """
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower() in ('true', '1', 'yes', 'on')
    return bool(value)

# Test mode flag (used by some components), but does not alter core settings
TEST_MODE = str_to_bool(os.getenv("TEST_MODE", "False"))
if any('pytest' in arg for arg in sys.argv):
    TEST_MODE = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str_to_bool(os.getenv('DEBUG', 'False'))

# Parse ALLOWED_HOSTS from environment, filter empty strings
_env_hosts = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Azure Container Apps internal health probes use IPs in 100.x.x.x and 10.x.x.x ranges
# These are handled by AzureHealthProbeMiddleware which rewrites the Host header.
# The middleware MUST be first in the MIDDLEWARE list.
AZURE_CONTAINER_INTERNAL_HOSTS = [
    '.azurecontainerapps.io',  # All Azure Container Apps domains
    '.azurestaticapps.net',    # All Azure Static Web Apps domains
    'admin.sautai.com',        # Django admin subdomain (Cloudflare-proxied)
    'localhost',
    '127.0.0.1',
]

ALLOWED_HOSTS = _env_hosts + AZURE_CONTAINER_INTERNAL_HOSTS

# Trust X-Forwarded-Host header from Azure's reverse proxy
# This allows AzureHealthProbeMiddleware to rewrite the host for internal IPs
USE_X_FORWARDED_HOST = True

# Model quota limits
GPT41_AUTH_LIMIT = int(os.getenv('GPT41_AUTH_LIMIT', 5))  # gpt-5 per authenticated user / day
GPT41_MINI_GUEST_LIMIT = int(os.getenv('GPT41_MINI_GUEST_LIMIT', 10))  # gpt-5-mini per guest / day

# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chefs',
    'chef_services',
    'meals',
    'services',
    'reviews',
    'custom_auth',
    'django_countries',
    'chef_admin',
    'customer_dashboard',
    'local_chefs',
    'crm',
    'memberships',
    'messaging',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'stripe',
    'storages',
    'django_celery_beat',
]

# Feature flags
# Central kill-switch for the legacy meal-plan stack
LEGACY_MEAL_PLAN_ENABLED = str_to_bool(os.getenv('LEGACY_MEAL_PLAN_ENABLED', 'True'))
# Chef-focused pivot: disable consumer meal-plan/instruction emails unless explicitly re-enabled
MEAL_PLAN_EMAIL_NOTIFICATIONS_ENABLED = str_to_bool(
    os.getenv('MEAL_PLAN_EMAIL_NOTIFICATIONS_ENABLED', 'False')
)

MIDDLEWARE = [
    'utils.middleware.AzureHealthProbeMiddleware',  # Must be first - handles Azure health probes
    'corsheaders.middleware.CorsMiddleware',  # CORS must be as high as possible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'utils.middleware.CloudflareAccessMiddleware',
]

# CORS Configuration - Handle comma-separated origins from Key Vault
cors_origins_str = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_origins_str:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_str.split(',') if origin.strip()]
else:
    # Fallback if no CORS_ALLOWED_ORIGINS set
    CORS_ALLOWED_ORIGINS = [
        os.getenv('STREAMLIT_URL', 'https://sautai.com'),
        'https://sautai.com',
        'https://www.sautai.com',
        'https://api.sautai.com',
    ]

# Allow cookies/credentials to be sent by the browser
CORS_ALLOW_CREDENTIALS = True

# Allowed headers
CORS_ALLOW_HEADERS = [
    'Idempotency-Key',
    'idempotency-key',
    'Authorization',
    'Content-Type',
    'X-Requested-With',
]
# In development, ensure localhost origins for React/Vite are allowed
if DEBUG:
    CORS_ALLOWED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS + [
        'http://localhost:5173', 'http://127.0.0.1:5173',
        'http://localhost:5174', 'http://127.0.0.1:5174',
        'http://localhost:3000', 'http://127.0.0.1:3000',
        'http://localhost:8501', 'http://127.0.0.1:8501',
    ]))
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:5173', 'http://127.0.0.1:5173',
        'http://localhost:5174', 'http://127.0.0.1:5174',
        'http://localhost:3000', 'http://127.0.0.1:3000',
        'http://localhost:8000', 'http://127.0.0.1:8000',  # Django dev server
        'http://localhost:8501', 'http://127.0.0.1:8501',
    ]

# Session cookies must flow between the SPA and API domains when we serve the frontend separately.
# Default to the production value via env while keeping local dev behaviour unchanged.
SESSION_COOKIE_DOMAIN = os.getenv('SESSION_COOKIE_DOMAIN', None)
SESSION_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'
SESSION_COOKIE_SECURE = not DEBUG

ROOT_URLCONF = 'hood_united.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'custom_auth.context_processors.role_context_processor',
                'meals.context_processors.legacy_meal_plan_flags',
            ],
        },
    },
]

# WSGI_APPLICATION = 'hood_united.wsgi.application'
# Change from WSGI to ASGI
ASGI_APPLICATION = 'hood_united.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('TEST_DB_NAME'),
            'USER': os.getenv('TEST_DB_USER'),
            'PASSWORD': os.getenv('TEST_DB_PASSWORD'),
            'HOST': os.getenv('TEST_DB_HOST'),
            'PORT': os.getenv('TEST_DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            # Connection management for Azure PostgreSQL
            'CONN_MAX_AGE': 0,  # Don't persist connections - open fresh for each task/request
            'CONN_HEALTH_CHECKS': True,  # Test connection before each request (Django 4.1+)
            'OPTIONS': {
                'connect_timeout': 10,  # Connection timeout in seconds
                'options': '-c statement_timeout=60000',  # 60 second query timeout (for complex queries)
                'keepalives': 1,  # Enable TCP keepalives
                'keepalives_idle': 30,  # Start keepalives after 30s of idle
                'keepalives_interval': 10,  # Send keepalive every 10s
                'keepalives_count': 5,  # 5 failed keepalives = connection dead
            },
        }
    }

# Supabase database for migration (dual database support)
# Uses SUPA_DB_* environment variables
# Security: Use django_service role which bypasses RLS (not postgres superuser)
if os.getenv('SUPA_DB_HOST'):
    DATABASES['supabase'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('SUPA_DB_NAME', 'postgres'),
        'USER': os.getenv('SUPA_DB_USER', 'django_service'),  # Use dedicated service role
        'PASSWORD': os.getenv('SUPA_DB_PASSWORD'),
        'HOST': os.getenv('SUPA_DB_HOST'),
        'PORT': os.getenv('SUPA_DB_PORT', '5432'),
        'CONN_MAX_AGE': 0,
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': 10,
            'sslmode': 'require',  # Supabase requires SSL
            'options': '-c statement_timeout=60000',
        },
        # Skip creating test database for supabase - use default's test db
        'TEST': {
            'MIRROR': 'default',
        },
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Rest framework settings
# In development, support both Session and JWT auth to ease local testing.
# In production, keep JWT-only.
# NOTE: JWT must come first so API calls from the React frontend (which use JWT)
# don't trigger CSRF enforcement from SessionAuthentication when browser has session cookies.
_DEFAULT_AUTH_CLASSES = (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
    'rest_framework.authentication.SessionAuthentication',
) if DEBUG else (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
)

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'custom_auth.throttles.AuthenticatedBurstThrottle',
        'custom_auth.throttles.AuthenticatedDailyThrottle',
        'api.throttles.GPT4DailyThrottle',
        'api.throttles.GuestGPT4MiniThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day',
        'auth_burst': '60/min',
        'auth_daily': '15000/day',
        'gpt4': f'{GPT41_AUTH_LIMIT}/day',
        'gpt4_mini_guest': f'{GPT41_MINI_GUEST_LIMIT}/day',
        'user': '15000/day',
    },
    'DEFAULT_AUTHENTICATION_CLASSES': _DEFAULT_AUTH_CLASSES,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # ... other settings
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'en-us')

TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = str_to_bool(os.getenv('USE_TZ', 'True'))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Azure Blob Storage Configuration
AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME', 'sautaiblobstorage')
AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY')
AZURE_CONNECTION_STRING = os.getenv('AZURE_CONNECTION_STRING')  # Optional but recommended
AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'

# Static files directories - this applies to both DEBUG and production
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

if DEBUG:
    # Local development settings
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    
    # Use local storage for development
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # Production settings - Azure Blob Storage
    AZURE_MEDIA_CONTAINER = os.getenv('AZURE_CONTAINER', 'media')
    AZURE_STATIC_CONTAINER = os.getenv('AZURE_STATIC_CONTAINER', 'static')
    
    # Media and Static URLs
    MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{AZURE_MEDIA_CONTAINER}/'
    STATIC_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{AZURE_STATIC_CONTAINER}/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Still needed for collectstatic
    
    # Modern Django 4.2+ Azure Blob Storage Configuration
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": AZURE_ACCOUNT_NAME,
                "account_key": AZURE_ACCOUNT_KEY,
                "azure_container": AZURE_MEDIA_CONTAINER,
                "azure_ssl": True,
                "overwrite_files": False,  # Prevents overwriting files with same name
                "location": "",  # Root level of container
                "cache_control": "public,max-age=31536000,immutable",  # 1 year cache
                "object_parameters": {
                    "cache_control": "public,max-age=31536000,immutable",
                }
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": AZURE_ACCOUNT_NAME,
                "account_key": AZURE_ACCOUNT_KEY,
                "azure_container": AZURE_STATIC_CONTAINER,
                "azure_ssl": True,
                "overwrite_files": True,  # Allow overwriting static files
                "location": "",  # Root level of container
                "cache_control": "public,max-age=31536000,immutable",  # 1 year cache for static files
                "object_parameters": {
                    "cache_control": "public,max-age=31536000,immutable",
                }
            },
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'custom_auth.CustomUser'

AUTHENTICATION_BACKENDS = [
    'custom_auth.backends.CaseInsensitiveAuthBackend', # Custom backend
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]


# Login redirects
LOGIN_REDIRECT_URL = 'custom_auth:profile'
LOGIN_URL = 'custom_auth:login'


# AI API Configuration
# Primary AI Provider: Groq
GROQ_API_KEY = os.getenv('GROQ_API_KEY')
GROQ_MODEL = os.getenv('GROQ_MODEL', 'openai/gpt-oss-120b')

# OpenAI (used only for embeddings and Whisper audio transcription)
OPENAI_KEY = os.getenv('OPENAI_KEY')

SPOONACULAR_API_KEY = os.getenv('SPOONACULAR_API_KEY')

# Stripe API keys
STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET') #TODO: Add this to the config file

# Stripe Membership IDs (created per Stripe account - test vs live)
MEMBERSHIP_PRODUCT_ID = os.getenv('STRIPE_MEMBERSHIP_PRODUCT_ID', '')
MEMBERSHIP_MONTHLY_PRICE_ID = os.getenv('STRIPE_MEMBERSHIP_MONTHLY_PRICE_ID', '')
MEMBERSHIP_ANNUAL_PRICE_ID = os.getenv('STRIPE_MEMBERSHIP_ANNUAL_PRICE_ID', '')

# Telegram Bot Integration
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_USERNAME = os.getenv('TELEGRAM_BOT_USERNAME', 'SautaiChefBot')
TELEGRAM_WEBHOOK_SECRET = os.getenv('TELEGRAM_WEBHOOK_SECRET', '')

# Email settings - Mailgun REST API (via requests library)
MAILGUN_API_KEY = os.getenv('MAILGUN_API_KEY')
MAILGUN_SENDER_DOMAIN = os.getenv('MAILGUN_SENDER_DOMAIN')
MAILGUN_API_URL = os.getenv('MAILGUN_API_URL', 'https://api.mailgun.net/v3')

# Default sender email address
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@sautai.com')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)


# Redis connection details
REDIS_URL = os.getenv('REDIS_URL')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')

DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True
DJANGO_REDIS_LOGGER = 'django.request'

# Configure different cache backends for development vs production
if DEBUG:
    # Development: Use local memory cache (no Redis required)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
else:
    # Production: Use Redis with SSL (Upstash or other TLS-enabled Redis)
    RAW_REDIS_URL = os.getenv("REDIS_URL", "").strip()

    if not RAW_REDIS_URL:
        raise RuntimeError("REDIS_URL is not set")

    # Parse SSL options from URL query params (django-redis doesn't parse these)
    # Example: rediss://...?ssl_cert_reqs=none
    from urllib.parse import urlparse, parse_qs, urlunparse
    
    parsed_redis = urlparse(RAW_REDIS_URL)
    redis_query_params = parse_qs(parsed_redis.query)
    
    # Extract ssl_cert_reqs if present, then strip it from URL
    ssl_cert_reqs_value = redis_query_params.pop('ssl_cert_reqs', [None])[0]
    
    # Rebuild URL without ssl_cert_reqs (django-redis will error on unknown params)
    clean_query = '&'.join(f'{k}={v[0]}' for k, v in redis_query_params.items())
    CLEAN_REDIS_URL = urlunparse((
        parsed_redis.scheme,
        parsed_redis.netloc,
        parsed_redis.path,
        parsed_redis.params,
        clean_query,
        parsed_redis.fragment
    ))
    
    # Build CONNECTION_POOL_KWARGS with SSL settings
    connection_pool_kwargs = {}
    if ssl_cert_reqs_value:
        # Map string value to ssl constant
        import ssl
        ssl_cert_map = {
            'none': ssl.CERT_NONE,
            'optional': ssl.CERT_OPTIONAL,
            'required': ssl.CERT_REQUIRED,
        }
        ssl_cert_reqs_value_lower = ssl_cert_reqs_value.lower()
        if ssl_cert_reqs_value_lower in ssl_cert_map:
            connection_pool_kwargs['ssl_cert_reqs'] = ssl_cert_map[ssl_cert_reqs_value_lower]
    
    # For rediss:// URLs, ensure SSL is enabled
    if parsed_redis.scheme == 'rediss' and 'ssl_cert_reqs' not in connection_pool_kwargs:
        # Default to CERT_NONE for cloud Redis providers (Upstash, etc.)
        import ssl
        connection_pool_kwargs['ssl_cert_reqs'] = ssl.CERT_NONE

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": CLEAN_REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": 15,
                "SOCKET_TIMEOUT": 15,
                "RETRY_ON_TIMEOUT": True,
                "SOCKET_KEEPALIVE": True,
                "CONNECTION_POOL_KWARGS": connection_pool_kwargs,
            },
        }
    }

# Django Channels layer configuration
if DEBUG:
    # Development: Use in-memory channel layer
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    # Production: Use Redis channel layer
    # For SSL-enabled Redis (rediss://) like Upstash, we need to pass host config
    # as a dictionary with ssl_cert_reqs option to handle TLS connections properly
    
    # Build host config with SSL settings if using rediss://
    channel_host_config = {"address": CLEAN_REDIS_URL}
    if connection_pool_kwargs.get('ssl_cert_reqs') is not None:
        channel_host_config['ssl_cert_reqs'] = connection_pool_kwargs['ssl_cert_reqs']
    
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [channel_host_config],
            },
        },
    }

# =============================================================================
# CELERY SETTINGS - DECOMMISSIONED
# =============================================================================
# Celery workers have been replaced with synchronous task execution via QStash.
# Tasks are now executed directly when QStash triggers the webhook endpoints.
# This eliminates continuous Redis polling that was causing ~77,000 commands/day.
#
# The following settings are kept for reference but are no longer used:
# - CELERY_BROKER_URL: No longer needed (tasks run in Django request)
# - CELERY_RESULT_BACKEND: No longer needed (no async results)
# - All broker/worker settings: No longer needed (no workers running)
#
# To fully decommission:
# 1. Stop the sautai-celery-worker Azure Container App
# 2. Delete Redis keys: _kombu.binding.celery, _kombu.binding.celeryev, etc.
# 3. Remove CELERY_BROKER_URL from environment variables
# =============================================================================

# Keep minimal settings for any code that still imports from celery
CELERY_TASK_ALWAYS_EAGER = True  # Execute tasks synchronously in the same process
CELERY_TASK_EAGER_PROPAGATES = True  # Propagate exceptions from eager tasks

# QStash settings (serverless cron scheduler - replaces Celery Beat)
# Get signing keys from Upstash QStash console: https://console.upstash.com/qstash
QSTASH_CURRENT_SIGNING_KEY = os.getenv('QSTASH_CURRENT_SIGNING_KEY')
QSTASH_NEXT_SIGNING_KEY = os.getenv('QSTASH_NEXT_SIGNING_KEY')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',  # Use FileHandler instead of RotatingFileHandler
            'filename': os.path.join(BASE_DIR, 'django_warnings.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'customer_dashboard': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django_redis': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'DEBUG', #TODO: Change to WARNING
            'propagate': True,
        },
        'messaging': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    }
}
# Email assistant session durations
# - Duration for authenticated email assistant sessions (hours)
# - Default expiry for generic email sessions in models fallback
EMAIL_ASSISTANT_SESSION_DURATION_HOURS = 72
EMAIL_SESSION_EXPIRY_HOURS = 72
# Environment-aware security settings
IS_PRODUCTION = not DEBUG and not TEST_MODE

if IS_PRODUCTION:
    # Production-only security settings
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Allow session cookies in cross-origin requests (needed for separate frontend)
    SESSION_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SAMESITE = 'None'
    # Build CSRF_TRUSTED_ORIGINS from CORS_ALLOWED_ORIGINS and additional domains
    CSRF_TRUSTED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS + [
        'https://sautai.com',
        'https://www.sautai.com',
        'https://admin.sautai.com',
        'https://*.127.0.0.1'
    ]))

    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    # SSL redirect - ONLY in production
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Development/Testing settings - NO SSL enforcement
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0

    # Clickjacking Protection
    X_FRAME_OPTIONS = 'DENY'

    # Other security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Error Reporting Configuration
# TODO: Add Sentry DSN for production error tracking
# SENTRY_DSN = os.getenv('SENTRY_DSN', '')
# See utils/error_reporting.py for integration guide
#
# When ready to integrate Sentry:
# 1. pip install sentry-sdk
# 2. Add SENTRY_DSN environment variable
# 3. Uncomment and configure sentry_sdk.init() below
#
# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration
# from sentry_sdk.integrations.celery import CeleryIntegration
# if os.getenv('SENTRY_DSN'):
#     sentry_sdk.init(
#         dsn=os.getenv('SENTRY_DSN'),
#         integrations=[DjangoIntegration(), CeleryIntegration()],
#         traces_sample_rate=0.1,
#         send_default_pii=False,
#     )

# MEHKO / IFSI compliance
# Platform fee percentage shown to consumers on MEHKO chef profiles (IFSI fee transparency requirement)
MEHKO_PLATFORM_FEE_PERCENT = float(os.getenv('MEHKO_PLATFORM_FEE_PERCENT', '5.0'))
