# Generated by Django 5.2.6 on 2025-12-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_services', '0007_connection_activity_and_chef_meal_plans'),
        ('chefs', '0023_add_sous_chef_emoji'),
        ('meals', '0075_add_meal_plan_generation_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefPrepPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start_date', models.DateField()),
                ('plan_end_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopping_list', models.JSONField(blank=True, help_text='Aggregated shopping list with timing suggestions', null=True)),
                ('batch_suggestions', models.JSONField(blank=True, help_text='AI-generated batch cooking recommendations', null=True)),
                ('total_meals', models.PositiveIntegerField(default=0)),
                ('total_servings', models.PositiveIntegerField(default=0)),
                ('unique_ingredients', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_plans', to='chefs.chef')),
            ],
            options={
                'ordering': ['-plan_start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChefPrepPlanCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_type', models.CharField(choices=[('meal_event', 'Meal Event'), ('service_order', 'Service Order')], max_length=20)),
                ('service_date', models.DateField()),
                ('servings', models.PositiveIntegerField(default=1)),
                ('meal_name', models.CharField(blank=True, max_length=200)),
                ('meal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_plan_links', to='meals.chefmealevent')),
                ('prep_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='chefs.chefprepplan')),
                ('service_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prep_plan_links', to='chef_services.chefserviceorder')),
            ],
            options={
                'ordering': ['service_date'],
            },
        ),
        migrations.CreateModel(
            name='ChefPrepPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('shelf_life_days', models.PositiveIntegerField(help_text='Estimated shelf life in days')),
                ('storage_type', models.CharField(choices=[('refrigerated', 'Refrigerated'), ('frozen', 'Frozen'), ('pantry', 'Pantry/Dry'), ('counter', 'Counter')], default='refrigerated', max_length=20)),
                ('earliest_use_date', models.DateField(help_text='First meal needing this ingredient')),
                ('latest_use_date', models.DateField(help_text='Last meal needing this ingredient')),
                ('suggested_purchase_date', models.DateField(help_text='Calculated optimal purchase date based on shelf life')),
                ('timing_status', models.CharField(choices=[('optimal', 'Optimal'), ('tight', 'Tight'), ('problematic', 'Problematic'), ('impossible', 'Impossible')], default='optimal', max_length=20)),
                ('timing_notes', models.TextField(blank=True, help_text='Explanation of timing considerations')),
                ('meals_using', models.JSONField(help_text='List of meal names and dates using this ingredient')),
                ('is_purchased', models.BooleanField(default=False)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('purchased_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prep_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chefs.chefprepplan')),
            ],
            options={
                'ordering': ['suggested_purchase_date', 'ingredient_name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, help_text='Estimated shelf life in days, determined by AI', null=True)),
                ('storage_type', models.CharField(choices=[('refrigerated', 'Refrigerated'), ('frozen', 'Frozen'), ('pantry', 'Pantry/Dry'), ('counter', 'Counter')], default='refrigerated', max_length=20)),
                ('shelf_life_updated_at', models.DateTimeField(blank=True, help_text='When shelf life was last determined/refreshed', null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='meals.dish')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='chefprepplan',
            index=models.Index(fields=['chef', '-plan_start_date'], name='chefs_chefp_chef_id_b4475e_idx'),
        ),
        migrations.AddIndex(
            model_name='chefprepplan',
            index=models.Index(fields=['chef', 'status'], name='chefs_chefp_chef_id_77cadc_idx'),
        ),
        migrations.AddConstraint(
            model_name='chefprepplan',
            constraint=models.CheckConstraint(check=models.Q(('plan_end_date__gte', models.F('plan_start_date'))), name='prep_plan_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='chefprepplancommitment',
            index=models.Index(fields=['prep_plan', 'service_date'], name='chefs_chefp_prep_pl_847018_idx'),
        ),
        migrations.AddIndex(
            model_name='chefprepplancommitment',
            index=models.Index(fields=['prep_plan', 'commitment_type'], name='chefs_chefp_prep_pl_3496cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='chefprepplancommitment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('commitment_type', 'meal_event'), ('meal_event__isnull', False), ('service_order__isnull', True)), models.Q(('commitment_type', 'service_order'), ('meal_event__isnull', True), ('service_order__isnull', False)), _connector='OR'), name='commitment_type_matches_reference'),
        ),
        migrations.AddIndex(
            model_name='chefprepplanitem',
            index=models.Index(fields=['prep_plan', 'ingredient_name'], name='chefs_chefp_prep_pl_78c1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chefprepplanitem',
            index=models.Index(fields=['prep_plan', 'suggested_purchase_date'], name='chefs_chefp_prep_pl_8b6fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='chefprepplanitem',
            index=models.Index(fields=['prep_plan', 'timing_status'], name='chefs_chefp_prep_pl_bd15bd_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['dish', 'name'], name='chefs_recip_dish_id_bdb7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['name'], name='chefs_recip_name_f53aad_idx'),
        ),
    ]
