# Generated by Django 5.2.10 on 2026-02-28 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0039_add_notify_cert_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='county',
            field=models.CharField(blank=True, help_text='County or jurisdiction for MEHKO operations', max_length=100),
        ),
        migrations.AddField(
            model_name='chef',
            name='mehko_active',
            field=models.BooleanField(default=False, help_text='MEHKO compliance complete: permit + consent + food handler cert verified'),
        ),
        migrations.AddField(
            model_name='chef',
            name='mehko_consent',
            field=models.BooleanField(default=False, help_text='Chef consented to CDPH disclosures and complaint reporting per §114367.6'),
        ),
        migrations.AddField(
            model_name='chef',
            name='permit_expiry',
            field=models.DateField(blank=True, help_text='MEHKO permit expiration date', null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='permit_number',
            field=models.CharField(blank=True, help_text='MEHKO permit number issued by local enforcement agency', max_length=100),
        ),
        migrations.AddField(
            model_name='chef',
            name='permitting_agency',
            field=models.CharField(blank=True, help_text='Local enforcement agency that issued the MEHKO permit', max_length=200),
        ),
        migrations.AlterField(
            model_name='chefverificationdocument',
            name='doc_type',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('background', 'Background Check'), ('food_handlers', 'Food Handler Certificate'), ('permit', 'MEHKO Permit'), ('other', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='MehkoComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField(help_text='Description of the complaint')),
                ('is_significant', models.BooleanField(default=False, help_text='Significant food safety complaint requiring same-day buyer list')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reported_to_agency', models.BooleanField(default=False, help_text='Whether this complaint has been reported to local enforcement')),
                ('reported_at', models.DateTimeField(blank=True, help_text='When this complaint was reported to local enforcement', null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this complaint was resolved', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about complaint handling')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mehko_complaints', to='chefs.chef')),
                ('complainant', models.ForeignKey(blank=True, help_text='User who filed the complaint (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_mehko_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['chef', '-submitted_at'], name='chefs_mehko_chef_id_b5af35_idx'), models.Index(fields=['chef', 'reported_to_agency'], name='chefs_mehko_chef_id_acd976_idx')],
            },
        ),
    ]
