# Generated by Django 5.2.10 on 2026-02-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0040_chef_county_chef_mehko_active_chef_mehko_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefnotification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('birthday', 'Birthday reminder'), ('anniversary', 'Anniversary reminder'), ('followup', 'Follow-up suggestion'), ('todo', 'To-do reminder'), ('seasonal', 'Seasonal suggestion'), ('milestone', 'Client milestone'), ('tip', 'Contextual tip'), ('system', 'System notification'), ('cert_expiry', 'Certification expiry'), ('permit_expiry', 'MEHKO permit expiry')], default='system', max_length=20),
        ),
    ]
