# Generated by Django 5.2.10 on 2026-02-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0041_alter_chefnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefnotification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('birthday', 'Birthday reminder'), ('anniversary', 'Anniversary reminder'), ('followup', 'Follow-up suggestion'), ('todo', 'To-do reminder'), ('seasonal', 'Seasonal suggestion'), ('milestone', 'Client milestone'), ('tip', 'Contextual tip'), ('system', 'System notification'), ('cert_expiry', 'Certification expiry'), ('permit_expiry', 'MEHKO permit expiry'), ('complaint_threshold', 'MEHKO complaint threshold'), ('revenue_warning', 'MEHKO revenue warning')], default='system', max_length=20),
        ),
    ]
