# Generated by Django 5.2.10 on 2026-02-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0042_alter_chefnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='mehko_consent_at',
            field=models.DateTimeField(blank=True, help_text='When chef accepted MEHKO consent (audit trail)', null=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='mehko_consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address when MEHKO consent was given (audit trail)', null=True),
        ),
        migrations.AddField(
            model_name='mehkocomplaint',
            name='incident_date',
            field=models.DateField(blank=True, help_text='Date the food safety incident occurred (for buyer list lookups)', null=True),
        ),
    ]
