# Generated by Django 5.2.10 on 2026-02-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0043_chef_mehko_consent_at_chef_mehko_consent_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MehkoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_meal_cap', models.PositiveIntegerField(default=30, help_text='Max meals per day per MEHKO (§113825)')),
                ('weekly_meal_cap', models.PositiveIntegerField(default=90, help_text='Max meals per week per MEHKO (AB 1325)')),
                ('annual_revenue_cap', models.PositiveIntegerField(default=100000, help_text='Annual gross sales cap in dollars (AB 1325, CPI-adjusted)')),
                ('effective_date', models.DateField(help_text='When these limits take effect')),
                ('notes', models.TextField(blank=True, help_text="e.g. 'CPI adjustment for 2027, per CDPH bulletin XYZ'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MEHKO Configuration',
                'verbose_name_plural': 'MEHKO Configurations',
                'ordering': ['-effective_date'],
            },
        ),
    ]
