# Generated by Django 4.2 on 2026-04-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0044_mehkoconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
