# Generated by Django 4.2 on 2026-04-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0045_add_created_at_to_chefrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefpaymentlink',
            name='exchange_rate',
            field=models.FloatField(blank=True, help_text='Stripe exchange rate used (null when no conversion needed)', null=True),
        ),
        migrations.AddField(
            model_name='chefpaymentlink',
            name='settled_amount_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Amount in account settlement currency (from Stripe balance transaction)', null=True),
        ),
        migrations.AddField(
            model_name='chefpaymentlink',
            name='settled_currency',
            field=models.CharField(blank=True, help_text='Settlement currency (typically USD for US accounts)', max_length=3, null=True),
        ),
    ]
