# Generated by Django 5.2.10 on 2026-02-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0042_add_allergies_to_householdmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mehko_disclosure_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When user accepted MEHKO home kitchen food safety disclosures', null=True),
        ),
    ]
