# Generated by Django 5.2.10 on 2026-02-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_services', '0008_alter_chefservicepricetier_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefserviceorder',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('self_delivery', 'Chef/Household Delivery'), ('customer_pickup', 'Customer Pickup'), ('third_party', 'Third-Party Delivery')], default='customer_pickup', max_length=20),
        ),
    ]
