# Generated by Django 5.2.10 on 2026-02-28 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_services', '0009_chefserviceorder_delivery_method'),
        ('chefs', '0043_chef_mehko_consent_at_chef_mehko_consent_ip_and_more'),
        ('custom_auth', '0043_customuser_mehko_disclosure_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chefserviceorder',
            name='charged_amount_cents',
            field=models.PositiveIntegerField(default=0, help_text='Amount in smallest currency unit, captured at order creation time'),
        ),
        migrations.AddIndex(
            model_name='chefserviceorder',
            index=models.Index(fields=['chef', 'service_date', 'status'], name='chef_servic_chef_id_cf4c23_idx'),
        ),
    ]
